import { colors, danger, warning, success, info } from '@styles/config/utilities'
import { rgba } from 'polished'

export const Palette = {
	light: {
		name: 'light',
		common: {
			black: colors.black,
			white: colors.white,
		},
		background: {
			default: colors.neutral08,
			card: colors.neutral00,
			paper: colors.neutral05,
			body: colors.neutral06,
		},
		text: {
			primary: rgba(colors.neutral90, 0.87),
			secondary: rgba(colors.neutral90, 0.54),
			disabled: rgba(colors.neutral90, 0.38),
			hint: rgba(colors.neutral90, 0.38),
		},
		primary: {
			light: colors.red10,
			main: colors.red50,
			dark: colors.red70,
		},
		secondary: {
			light: colors.blue10,
			main: colors.blue50,
			dark: colors.blue70,
		},
		warning: {
			light: warning.light,
			main: warning.main,
			dark: warning.dark,
		},
		danger: {
			light: danger.light,
			main: danger.main,
			dark: danger.dark,
		},
		success: {
			light: success.light,
			main: success.main,
			dark: success.dark,
		},
		info: {
			light: info.light,
			main: info.main,
			dark: info.dark,
		},
		neutral: {
			'00': colors.neutral00,
			'05': colors.neutral05,
			'06': colors.neutral06,
			'07': colors.neutral07,
			'08': colors.neutral08,
			'09': colors.neutral09,
			10: colors.neutral10,
			20: colors.neutral20,
			30: colors.neutral30,
			40: colors.neutral50,
			50: colors.neutral50,
			60: colors.neutral60,
			70: colors.neutral70,
			80: colors.neutral80,
			90: colors.neutral90,
		},
		divider: rgba(colors.neutral60, 0.12),
		action: {
			active: rgba(colors.neutral60, 0.54),
			hover: rgba(colors.neutral60, 0.04),
			hoverOpacity: 0.04,
			selected: rgba(colors.neutral60, 0.08),
			selectedOpacity: 0.08,
			disabled: rgba(colors.neutral60, 0.26),
			disabledBackground: rgba(colors.neutral60, 0.12),
			disabledOpacity: 0.38,
			focus: rgba(colors.neutral60, 0.12),
			focusOpacity: 0.12,
			activatedOpacity: 0.12,
		},
	},
	dark: {
		name: 'dark',
		common: {
			black: colors.black,
			white: colors.white,
		},
		background: {
			default: colors.neutral50,
			card: colors.neutral60,
			paper: colors.neutral70,
			body: colors.neutral90,
		},
		text: {
			primary: rgba(colors.neutral00, 0.87),
			secondary: rgba(colors.neutral00, 0.54),
			disabled: rgba(colors.neutral00, 0.38),
			hint: rgba(colors.neutral00, 0.38),
		},
		primary: {
			light: colors.red10,
			main: colors.red50,
			dark: colors.red70,
		},
		secondary: {
			light: colors.blue10,
			main: colors.blue50,
			dark: colors.blue70,
		},
		warning: {
			light: warning.light,
			main: warning.main,
			dark: warning.dark,
		},
		danger: {
			light: danger.light,
			main: danger.main,
			dark: danger.dark,
		},
		success: {
			light: success.light,
			main: success.main,
			dark: success.dark,
		},
		info: {
			light: info.light,
			main: info.main,
			dark: info.dark,
		},
		neutral: {
			'00': colors.neutral90,
			'05': colors.neutral80,
			'06': colors.neutral70,
			'07': colors.neutral60,
			'08': colors.neutral50,
			'09': colors.neutral40,
			10: colors.neutral30,
			20: colors.neutral20,
			30: colors.neutral10,
			40: colors.neutral09,
			50: colors.neutral08,
			60: colors.neutral07,
			70: colors.neutral06,
			80: colors.neutral05,
			90: colors.neutral00,
		},
		divider: rgba(colors.neutral00, 0.12),
		action: {
			active: rgba(colors.neutral00, 0.54),
			hover: rgba(colors.neutral00, 0.04),
			hoverOpacity: 0.04,
			selected: rgba(colors.neutral00, 0.08),
			selectedOpacity: 0.08,
			disabled: rgba(colors.neutral00, 0.26),
			disabledBackground: rgba(colors.neutral00, 0.12),
			disabledOpacity: 0.38,
			focus: rgba(colors.neutral00, 0.12),
			focusOpacity: 0.12,
			activatedOpacity: 0.12,
		},
	},
	contrastThreshold: 3,
	tonalOffset: 0.04,
}
